### ISSUE TITLE
polyparse doesn't build with GHC 8.8.1

### ISSUE THREAD

**Issue by recursion-ninja** [hackage-trustees/malcolm-wallace-universe#3]
As I mentioned [here](https://github.com/haskell-infra/hackage-trustees/issues/222), `polyparse` doesn't build with GHC 8.8.1.

```
polyparse                   > configure
polyparse                   > Configuring polyparse-1.12.1...
polyparse                   > build
polyparse                   > Preprocessing library for polyparse-1.12.1..
polyparse                   > Building library for polyparse-1.12.1..
polyparse                   > [ 1 of 18] Compiling Text.ParserCombinators.HuttonMeijer
polyparse                   > 
polyparse                   > /tmp/stack22733/polyparse-1.12.1/src/Text/ParserCombinators/HuttonMeijer.hs:66:4: error:
polyparse                   >     ‘fail’ is not a (visible) method of class ‘Monad’
polyparse                   >    |
polyparse                   > 66 |    fail            = Fail.fail
polyparse                   >    |    ^^^^
polyparse                   > 
```

The source code appears to need to be updated with CPP guards or a new version that isn't backwards compatible.

**Comment by phadej** [comment]
1.13 version uploaded
